"""YOLOX domain training guide + export helper (Apache-2.0).

This script does NOT import ultralytics. Training runs in the official YOLOX
repo (Megvii-BaseDetection/YOLOX, Apache-2.0). This file prepares data and
prints the exact commands to train + export OpenVINO IR for the app.

Workflow
--------
1. Build / label a dataset under ``yolox_dataset/`` (images + labels).
2. Convert to COCO:
       python tools/convert_yolo_to_coco.py yolo_dataset/
3. Clone YOLOX (once):
       git clone https://github.com/Megvii-BaseDetection/YOLOX.git
       cd YOLOX && pip install -r requirements.txt && python setup.py develop
4. Run this helper:
       python training/train_yolox_dataset.py --yolox-dir ../YOLOX
5. Copy exported IR AND labels.json (written next to it, see below) into
   ``models/custom/`` (or set ``yolox_model_xml`` in config).

The app's detector expects raw-grid ONNX/IR exports (no decode baked in) —
same as ``tools/get_yolox_model.py``. Use YOLOX's official export, then
``openvino.convert_model`` or ``tools/get_yolox_model.py``'s conversion path.

Class names: unlike an ultralytics export, YOLOX's own export tooling embeds
no class-name metadata into the ONNX/IR file at all — a raw-grid export is
just weights. ``modules.vision.detection_backend.names_from_model`` can only recover
names from that embedded metadata, so without a ``labels.json`` sidecar next
to the exported model, the app finds zero class names, logs "No class names
for custom model", and silently falls back to the 80-class COCO detector. This
script writes that sidecar automatically now; see ``--write-labels-only``
below to backfill one for a model you already exported.
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent


def _ensure_coco(dataset_dir: Path) -> tuple[Path, Path]:
    train_json = dataset_dir / "coco_train.json"
    val_json = dataset_dir / "coco_val.json"
    if train_json.is_file() and val_json.is_file():
        return train_json, val_json

    convert_tool = REPO_ROOT / "tools" / "convert_yolo_to_coco.py"
    print("COCO annotations missing — running convert_yolo_to_coco.py …")
    subprocess.check_call([sys.executable, str(convert_tool), str(dataset_dir)])
    if not train_json.is_file():
        raise FileNotFoundError(f"Expected {train_json} after conversion")
    return train_json, val_json


def class_names_from_coco(coco_path: Path) -> list[str]:
    """Class names in category-id order — the order YOLOX trains and predicts
    with, so this is the one authoritative source for them."""
    data = json.loads(coco_path.read_text(encoding="utf-8"))
    cats = sorted(data.get("categories", []), key=lambda c: c["id"])
    return [str(c["name"]) for c in cats]


def write_labels_json(names: list[str], out_path: Path) -> Path:
    """Write ``names`` as the plain-list shape ``load_class_names`` reads.

    This is the file ``modules.vision.detection_backend._custom()`` looks for beside
    a custom model's ``.xml``/``.onnx`` — see the module docstring for why it
    has to exist at all for a YOLOX export.
    """
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(names, indent=1), encoding="utf-8")
    return out_path


def _write_exp_py(yolox_dir: Path, dataset_dir: Path, num_classes: int,
                  depth: float, width: float, input_size: int) -> Path:
    """Minimal YOLOX Exp stub pointing at our COCO JSON + image folders."""
    exp_dir = yolox_dir / "exps" / "videohighlighter"
    exp_dir.mkdir(parents=True, exist_ok=True)
    exp_path = exp_dir / "custom_dataset.py"
    exp_path.write_text(f'''# Auto-generated by training/train_yolox.py — edit as needed.
import os
from yolox.exp import Exp as MyExp


class Exp(MyExp):
    def __init__(self):
        super().__init__()
        self.num_classes = {num_classes}
        self.depth = {depth}
        self.width = {width}
        self.input_size = ({input_size}, {input_size})
        self.test_size = ({input_size}, {input_size})
        self.exp_name = "videohighlighter_custom"
        self.data_dir = r"{dataset_dir.as_posix()}"
        self.train_ann = "coco_train.json"
        self.val_ann = "coco_val.json"
        self.data_num_workers = 4
        self.max_epoch = 80
        self.no_aug_epochs = 15
        self.basic_lr_per_img = 0.01 / 64.0
        self.scheduler = "yoloxwarmcos"
        self.eval_interval = 5
        self.save_history_ckpt = False

    def get_data_loader(self, batch_size, is_distributed, no_aug=False, cache_img=False):
        from yolox.data import COCODataset, TrainTransform, YoloBatchSampler, DataLoader
        from yolox.data.datasets.mosaicdetection import MosaicDetection
        import torch

        dataset = COCODataset(
            data_dir=self.data_dir,
            json_file=self.train_ann if not no_aug else self.val_ann,
            name="",
            img_size=self.input_size,
            preproc=TrainTransform(max_labels=50, flip_prob=0.5, hsv_prob=1.0),
            cache=cache_img,
        )
        if not no_aug:
            dataset = MosaicDetection(
                dataset,
                mosaic=True,
                mixup=True,
                img_size=self.input_size,
                preproc=TrainTransform(max_labels=50, flip_prob=0.5, hsv_prob=1.0),
            )
        sampler = YoloBatchSampler(
            sampler=torch.utils.data.SequentialSampler(dataset),
            batch_size=batch_size,
            drop_last=False,
            mosaic=not no_aug,
        )
        return DataLoader(dataset, batch_sampler=sampler, num_workers=self.data_num_workers, pin_memory=True)

    def get_eval_loader(self, batch_size, is_distributed, testdev=False, legacy=False):
        from yolox.data import COCODataset, ValTransform, DataLoader
        import torch
        valdataset = COCODataset(
            data_dir=self.data_dir,
            json_file=self.val_ann,
            name="",
            img_size=self.test_size,
            preproc=ValTransform(legacy=legacy),
        )
        sampler = torch.utils.data.SequentialSampler(valdataset)
        return DataLoader(valdataset, batch_size=batch_size, shuffle=False, num_workers=self.data_num_workers, pin_memory=True)
''', encoding="utf-8")
    return exp_path


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Prepare + print YOLOX training commands")
    parser.add_argument("--dataset", type=Path, default=REPO_ROOT / "yolox_dataset")
    parser.add_argument("--yolox-dir", type=Path,
                        help="Path to cloned Megvii-BaseDetection/YOLOX repo "
                             "(not needed with --write-labels-only)")
    parser.add_argument("--size", choices=("nano", "tiny", "s", "m", "l", "x"), default="s")
    parser.add_argument("--epochs", type=int, default=80)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--dry-run", action="store_true", help="Only write exp file, don't print train cmd")
    parser.add_argument("--write-labels-only", type=Path, metavar="OUT_PATH",
                        help="Backfill labels.json for an ALREADY-exported model — "
                             "e.g. --write-labels-only models/custom/labels.json. "
                             "Reads class names from --dataset's coco_train.json; "
                             "does not need --yolox-dir or touch training at all.")
    args = parser.parse_args(argv)

    dataset_dir = args.dataset.resolve()

    if args.write_labels_only:
        train_json, _ = _ensure_coco(dataset_dir)
        names = class_names_from_coco(train_json)
        if not names:
            print(f"No categories in {train_json} — check dataset labels.")
            return 1
        out = write_labels_json(names, args.write_labels_only.resolve())
        print(f"✅ Wrote {len(names)} class name(s) → {out}")
        print(f"   {names}")
        return 0

    if not args.yolox_dir:
        print("--yolox-dir is required unless --write-labels-only is given.")
        return 1

    yolox_dir = args.yolox_dir.resolve()
    if not yolox_dir.is_dir():
        print(f"YOLOX repo not found: {yolox_dir}")
        print("Clone: git clone https://github.com/Megvii-BaseDetection/YOLOX.git")
        return 1

    train_json, _ = _ensure_coco(dataset_dir)
    names = class_names_from_coco(train_json)
    num_classes = len(names)
    if num_classes == 0:
        print("No categories in COCO JSON — check dataset labels.")
        return 1

    size_table = {
        "nano": (0.33, 0.25, 416),
        "tiny": (0.33, 0.375, 416),
        "s": (0.33, 0.50, 640),
        "m": (0.67, 0.75, 640),
        "l": (1.0, 1.0, 640),
        "x": (1.33, 1.25, 640),
    }
    depth, width, input_size = size_table[args.size]
    exp_path = _write_exp_py(yolox_dir, dataset_dir, num_classes, depth, width, input_size)
    exp_module = "exps.videohighlighter.custom_dataset"

    # Written now, at prep time, rather than after training: the names never
    # change once the COCO json is fixed, and having this ready before
    # training even starts means there is nothing left to remember afterwards.
    labels_path = write_labels_json(names, dataset_dir / "labels.json")

    print(f"\n✅ Wrote YOLOX experiment: {exp_path}")
    print(f"   Classes: {num_classes}  Size: YOLOX-{args.size}  Input: {input_size}\n")
    print(f"✅ Wrote class names: {labels_path}")
    print(f"   {names}\n")
    print("Run training from the YOLOX repo root:\n")
    print(f"  cd {yolox_dir}")
    print(f"  python tools/train.py -f {exp_module} -d 1 -b {args.batch_size} "
          f"--fp16 -o -c path/to/yolox_{args.size}.pth")
    print("\nAfter training, export ONNX (no decode_in_inference) and convert:\n")
    print(f"  python tools/export_onnx.py --output-name yolox_{args.size}.onnx "
          f"-f {exp_module} -c YOLOX_outputs/.../best_ckpt.pth")
    print(f"  python {REPO_ROOT / 'tools' / 'get_yolox_model.py'}  # or openvino.convert_model on the ONNX")
    print(f"\nThe app reads class names from a labels.json sitting NEXT TO the "
          f"model file — the exported .onnx/.xml carries no names of its own:")
    print(f"  Copy IR   → {REPO_ROOT / 'models' / 'custom' / f'yolox_{args.size}.xml'}")
    print(f"  Copy names → {REPO_ROOT / 'models' / 'custom' / 'labels.json'}  "
          f"(from {labels_path})\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
